apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-mdt-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-mdt-tracker
  template:
    metadata:
      labels:
        app: patient-mdt-tracker
    spec:
      containers:
      - name: patient-mdt-tracker
        image: patient_mdt_tracker:latest
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: patient-mdt-tracker
spec:
  selector:
    app: patient-mdt-tracker
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer
